### PR TITLE
Move class methods in KafoConfigure together

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
[test kafo]

**Review by wbclark — COMMENTED** [review]
@ehelms could you provide a brief explanation of how this supports #299 ?

**Comment by ehelms** [comment]
Overall, this is just a clean up re-factoring that makes following or seeing where the code lives easier. It only supports #299 in the case that due to the changes around options in it, this re-organization of the code makes that easier to follow and easier to clean up.

**Review by wbclark — APPROVED** [review]
Thanks @ehelms . I also wondered about the change from `def self.method_name` to `def method_name` but then I saw we already use `class << self` above.

This looks good to me.

**Pull request merged**
