### PR TITLE
fixes #16862 - register custom data types from module path

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ares** [comment]
it seems this does not work with puppet 4, not sure why but rdoc parsing fails on something

**Comment by domcleal** [comment]
@ares if you mean the failing tests, that should be fixed by https://github.com/theforeman/kafo_parsers/pull/26 (puppet-strings 0.99 has a different schema to 0.4).

**Comment by domcleal** [comment]
I've moved the registration of data types from KafoConfigure into Configuration#modules so they're registered when using kafo-export-params as well as the KafoConfigure installer runs. I was also able to add tests this way.

**Comment by ares** [comment]
Thanks @domcleal, merging!

**Pull request merged**
