### PR TITLE
fixes #19341 - remove invalid UTF-8 encoded chars from Puppet log

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by fatmcgav** [comment]
@domcleal That was quick :D 

Happy to test if can give me some pointers :)

**Comment by domcleal** [comment]
Applying the patch to your file at /usr/share/gems/gems/kafo-1.0.5/lib/kafo/puppet_log_parser.rb should fix it. I tested with the fact value in the Redmine issue and it did appear to run correctly again.

**Comment by fatmcgav** [comment]
Of course :) 

Applied the patch, and can confirm that foreman-installer ran through successfully. 

Cheers again for the quick fix...

**Comment by ares** [comment]
Thanks @domcleal, merging.

**Pull request merged**
