### PR TITLE
Add initial Rubocop configuration

### PR DESCRIPTION
**Pull request by ehelms**
Seeded configuration is from foreman-installer project and includes
all current offenses in a .rubocop_todo.yml to tackle.

### CODE REVIEW

**Comment by ehelms** [comment]
[test kafo]

**Comment by ehelms** [comment]
[test kafo]

**Comment by ehelms** [comment]
[test kafo]

**Comment by ehelms** [comment]
[test kafo]

**Review by wbclark — CHANGES_REQUESTED** [review]
Rakefile should also contain:

```
begin
  require 'rubocop/rake_task'
  RuboCop::RakeTask.new
rescue LoadError
  puts 'Rubocop not loaded'
end
```

**Comment by ehelms** [comment]
Their README (https://github.com/rubocop-hq/rubocop) does not mention using the rake task and so I was not sure if it was worth it or better to follow how the README specifies to run it?

**Comment by wbclark** [comment]
> Their README (https://github.com/rubocop-hq/rubocop) does not mention using the rake task and so I was not sure if it was worth it or better to follow how the README specifies to run it?

In the absence of a good reason not to do so, it would be nice to be consistent with the usage in foreman-installer.

In fact, now that you pointed this out, I ran `$ rubocop` vs. `$ bundle exec rake rubocop` in foreman-installer and saw different results (with Kafo I got the same result with either method, however). So there does appear to be some difference, even if it doesn't manifest here.

**Comment by ehelms** [comment]
What differences do you see?

```
root@centos7 foreman-installer (advanced-options)$ bundle exec rubocop
Inspecting 189 files
.............................................................................................................................................................................................

189 files inspected, no offenses detected
root@centos7 foreman-installer (advanced-options)$ bundle exec rake rubocop
Running RuboCop...
Inspecting 189 files
.............................................................................................................................................................................................

189 files inspected, no offenses detected
```

**Comment by wbclark** [comment]
Ah, here is the difference:

```
[wclark@mercury foreman-installer]$ bundle exec rake rubocop | tail -n1
189 files inspected, no offenses detected
[wclark@mercury foreman-installer]$ bundle exec rubocop | tail -n1
189 files inspected, no offenses detected
[wclark@mercury foreman-installer]$ rubocop | tail -n1
189 files inspected, 27 offenses detected, 15 offenses auto-correctable
[wclark@mercury foreman-installer]$ 
```

**Review by wbclark — APPROVED** [review]
I won't hold this up any longer. If we need the Rake we can add it later. Or maybe we should remove it from foreman-installer if it isn't actually necessary.

**Comment by ehelms** [comment]
@wbclark I added a small series of updates (including the rake task) to this PR to ensure that Rubocop is 'green' from the start so we can enable the CI job without it being broken.

**Pull request merged**
