### PR TITLE
Fixes #9509 - allow overriding by empty values

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by domcleal** [comment]
Not the prettiest thing, but I guess it's good!  The only improvement that comes to mind is supporting a --no-class-parameter argument, like the way we disable entire modules.

**Comment by ares** [comment]
then we'd have the same issue in interactive mode, and it's consistent with UNDEF we already have there

**Comment by domcleal** [comment]
I think you can set an empty array in interactive mode already though.

**Comment by ares** [comment]
when I tested I was unable to do that, it always got back to default value

**Comment by domcleal** [comment]
Ah alright.

**Comment by mmoll** [comment]
:+1:

**Comment by ares** [comment]
Thanks both of you, merging.

**Pull request merged**
