### PR TITLE
Make kafo exit codes great again

### PR DESCRIPTION
**Pull request by iNecas**
It took me a while to find the nice aligned set of exit codes
to give up that fast. I will be glad if you merge it, no hard
feeling if not. I like text alignment, as you can see here :)

### CODE REVIEW

**Comment by ares** [comment]
oh my :-) ok, seems harmless [test]

**Comment by dLobatog** [comment]
donald--make-kafo-exit-codes-great-again

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
Thank you, merging.

**Comment by iNecas** [comment]
:tada: Happy Friday :)

**Pull request merged**
