### PR TITLE
Remove password manager

### PR DESCRIPTION
**Pull request by ekohl**
541f90af875bb2640c2f9ec2739182a3f56077fd removed password support, but failed to remove the PasswordManager.

IMHO this can be a 3.1.0 release since it's not really an API we intend to expose but I'm open to other arguments.

### CODE REVIEW

**Comment by ares** [comment]
3.1.0 totally makes sense, it's not public API. We probably need to drop some tests as well.

**Comment by ares** [comment]
[test kafo] looks like random failures

**Comment by mmoll** [comment]
:green_heart:

**Comment by ares** [comment]
Thanks @ekohl, merging!

**Pull request merged**
