### PR TITLE
[WIP] Update gemfile

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by mmoll** [comment]
Is support for Rubies <2.0 really needed currently?

**Comment by ares** [comment]
well we still run tests on them and there was no need to drop it - http://ci.theforeman.org/job/test_kafo_parsers_master_pull_request/

but maybe it's time, if you want to drop it, I guess we should bump the version number

**Comment by ekohl** [comment]
[test kafo]

**Comment by iNecas** [comment]
Seems like this is good to go?

**Comment by ekohl** [comment]
Not really, the tests didn't actually run so that's why they're green.

**Comment by ekohl** [comment]
[test kafo]

**Pull request closed without merging**
