### PR TITLE
update clamp to >= 1.3.1

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
CI is broken for puppet 5 and 6, but I don't care: https://github.com/theforeman/jenkins-jobs/pull/335

**Comment by evgeni** [comment]
it's passing now for ruby 2.7/puppet 7

**Comment by evgeni** [comment]
I've fixed CI in https://github.com/theforeman/jenkins-jobs/pull/336, lets see

**Comment by evgeni** [comment]
[test kafo]

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Should we formally drop Puppet < 7 and Ruby < 2.7 support in a major version?

**Comment by evgeni** [comment]
We "should". There is https://projects.theforeman.org/issues/32611 for Puppet 5, with an unfinished PR.

**Comment by ekohl** [comment]
https://github.com/theforeman/kafo/pull/354

**Pull request merged**
