### PR TITLE
fixes #13802 - change File.realpath to Pathname for Ruby 1.8.7

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by iNecas** [comment]
Have not tested but the additional tests should be sufficient prove it helps.The change from code-perspective looks reasonable. ACK

**Comment by ares** [comment]
Thanks @domcleal, merging. Do you want me to release 0.7.2 with the fix?

**Comment by domcleal** [comment]
@ares yes, please as it's affecting nightlies and 1.11.

**Comment by ares** [comment]
https://github.com/theforeman/foreman-packaging/pull/1035
https://github.com/theforeman/foreman-packaging/pull/1036

**Pull request merged**
