### PR TITLE
Fixes #29830 - Remove deprecation warnings from use of must_ in minitest

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Seeing how this applies across Ruby versions. For refrence the deprecation warning is akin to:

```
DEPRECATED: global use of wont_include from /home/ehelms/workspace/upstream/kafo/test/test_helper.rb:199. Use _(obj).wont_include instead. This will fail in Minitest 6.
```

**Comment by ehelms** [comment]
[test kafo]

**Comment by mmoll** [comment]
[test kafo]

**Comment by ehelms** [comment]
[test kafo]

**Comment by ehelms** [comment]
Got it green now

**Comment by mmoll** [comment]
merged, thanks @ehelms!

**Pull request merged**
