### PR TITLE
Fixes #20109 - Call uniq on this array to ensure no duplicates

### PR DESCRIPTION
**Pull request by NeilHanlon**
Fixes #20109

### CODE REVIEW

**Comment by ekohl** [comment]
If you use ```Fixes #20109``` then redmine should link it and auto close it when it's merged. Other than that it looks correct.

**Comment by NeilHanlon** [comment]
Thanks!

**Comment by mmoll** [comment]
[test]

**Comment by NeilHanlon** [comment]
@mmoll That should be good, yes?

**Comment by ekohl** [comment]
We usually have ```Fixes #20109 - Handle duplicate modules``` (or something like that) so the git log shortlog is still useful.

**Comment by NeilHanlon** [comment]
No worries. I'll add that on. Just wasn't sure.

**Comment by ares** [comment]
[test] I can modify the message on merging, the patch seems reasonable to me

**Comment by mmoll** [comment]
💚

**Comment by NeilHanlon** [comment]
I won't force push a new git status, then; and I'll know for next time :)

**Comment by ares** [comment]
Thanks @NeilHanlon, merged as c2d0204306bcb1b8a6ed152603e0b34523a419b6

**Pull request closed without merging**
