### PR TITLE
Fixes #10500 - 'sort': comparison of Symbol with String failed (Argum…

### PR DESCRIPTION
**Pull request by johnkim76**
http://projects.theforeman.org/issues/10500
Fixes the above issue

Related to the PR below
https://github.com/theforeman/kafo/pull/110

### CODE REVIEW

**Comment by jwmatthews** [comment]
@mbacovsky please review and help us get this merged.  

This is needed for RHCI, it's currently blocking the fusor-installer from running.

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
A test for this would be nice as I don't see the source of mixing strings and symbols. Otherwise looks good to merge.

**Comment by mbacovsky** [comment]
As @ares suggested, I'm curious where the symbols are coming from.  :+1: otherwise.

**Comment by jwmatthews** [comment]
@ares @mbacovsky here is a snippet of what data we saw when this problem arose:

self.hooks[pre] = 
{
:reset_db=>#<Proc:0x00000003d15850@/sbin/fusor-installer:38>, 
"/usr/share/katello-installer/hooks/pre/10-reset_feature.rb"=>#<Proc:0x00000003eeaec8@/usr/share/gems/gems/kafo-0.6.5.6/lib/kafo/hooking.rb:32>, 
"/usr/share/katello-installer/hooks/pre/11-clear_pulp_data_feature.rb"=>#<Proc:0x00000003eeac48@/usr/share/gems/gems/kafo-0.6.5.6/lib/kafo/hooking.rb:32>, 
"/usr/share/katello-installer/hooks/pre/12-clear_puppet_environments_feature.rb"=>#<Proc:0x00000003eeaab8@/usr/share/gems/gems/kafo-0.6.5.6/lib/kafo/hooking.rb:32>, 
"/usr/share/katello-installer/hooks/pre/15-check_java.rb"=>#<Proc:0x00000003eea8d8@/usr/share/gems/gems/kafo-0.6.5.6/lib/kafo/hooking.rb:32>, 
"/usr/share/katello-installer/hooks/pre/16-set_umask.rb"=>#<Proc:0x00000003eea6d0@/usr/share/gems/gems/kafo-0.6.5.6/lib/kafo/hooking.rb:32>, 
"/usr/share/katello-installer/hooks/pre/20-certs_update.rb"=>#<Proc:0x00000003eea518@/usr/share/gems/gems/kafo-0.6.5.6/lib/kafo/hooking.rb:32>, 
"/usr/share/katello-installer/hooks/pre/30-upgrade.rb"=>#<Proc:0x00000003eea388@/usr/share/gems/gems/kafo-0.6.5.6/lib/kafo/hooking.rb:32>

}


The :reset_db is coming from 
https://github.com/fusor/fusor-installer/blob/master/bin/fusor-installer#L38

**Comment by mbacovsky** [comment]
@jwmatthews I see, that dind't came to my mind. But also this suggests that the sort wont work properly. We should probably also remove the path on https://github.com/johnkim76/kafo/blob/10500/lib/kafo/hooking.rb#L33
```ruby
register(hook_type, File.basename(file), &hook_block)
```

**Comment by johnkim76** [comment]
@ares @mbacovsky modified the exisiting unit test.  Please review. Thank you.

**Comment by jwmatthews** [comment]
@mbacovsky in regard to removing the "path" from https://github.com/johnkim76/kafo/blob/10500/lib/kafo/hooking.rb#L33 what about the case of multiple files with the same filename stored in different directories.  Would this be handled OK if the key is shortened to just the base filename?

@mbacovsky would it be possible to move this thought (changing https://github.com/johnkim76/kafo/blob/10500/lib/kafo/hooking.rb#L33) to a different PR?

If we could merge the fix for (https://github.com/johnkim76/kafo/blob/10500/lib/kafo/hooking.rb#L47) and get it built into Satellite, it'd unblock RHCI ISO testing.  With current Satellite build RHCI is broken and unable to proceed.

**Comment by mbacovsky** [comment]
@jwmatthews files with same name in different directories should be in different groups e.g. `hooks[:pre][:file]` and hooks[:pre_validation][:file]. It wont prevent you to manually register hook with same name, but that is possible even now.  

I think it is okay to remove path in different PR if such solution is good enough for you. The decision will have to wait on @ares though as don't have merge right here yet.

**Comment by jwmatthews** [comment]
@mbacovsky @ares please merge this and help it get built downstream.  Separate PR for the remote path suggestion sounds good. 

Would it be possible to merge this, cherry-pick downstream, and build on Monday?

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
Merging, thanks @johnkim76

**Comment by ares** [comment]
merged as 73a749b523f771a55d255b5d84ab4f1cb2087d4c

**Comment by johnkim76** [comment]
@ares thank you!

**Pull request closed without merging**
